[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow = "C6eakXoy9RSWRT8KkHCdoRrBsSDw8459x3Ju2Qx9bVWf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
